# Generated by Django 2.0.5 on 2020-03-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='completes',
            new_name='completed',
        ),
    ]
